### ISSUE TITLE
Calculate ionizing photon rate from black body spectrum

### ISSUE THREAD

**Issue by will-henney** [will-henney/globule-seminario#37]
The PION simulation code uses a black body approximation for the spectrum of the central star when calculating the ionization of hydrogen.  The input parameters that we can vary are the effective temperature and radius of the star. 

However, we want to be able to explicitly control the ionizing luminosity $Q_H$ so that we can compare with analytic models.  The task for @RobeReyes is to calculate the hydrogen ionizing luminosity of a black body source with radius $R_\star$ and effective temperature $T_\star$.  

In particular, for the WR124 parameters that we have been using:
```
RT_Rstar____0    18.0   # Radius of star in solar radii.
RT_Tstar____0    3.3e4     # Stellar effective temperature.
```

I suggest using `astropy.units` to help ensure that units are correct. You can either write your own Planck function routine or use `astropy.modelling.models.BlackBody()`.  The integration can be done with methods in `scipy.integrate`

**Comment by will-henney** [comment]
@RobeReyes please respond to this thread with an explanation of what equations you will be using before starting work on the programming

**Comment by will-henney** [comment]
We can test the results by comparing with this graph, which comes from [Leitherer et al 1990](https://ui.adsabs.harvard.edu/abs/1990ApJS...73....1L/abstract)

![CleanShot 2023-08-30 at 20 51 51](https://github.com/will-henney/globule-seminario/assets/161264/f8a9c1b1-99f0-4ce0-87aa-d6136003e389)

Note that these results are for the little $q$, which is *surface flux* instead of *lumihosity*, so it doe snot include the factor of $4 \pi R_*^2$. 

![CleanShot 2023-08-30 at 20 58 19](https://github.com/will-henney/globule-seminario/assets/161264/c3565019-e9d6-45b7-b863-646755273f97)

and the $F_\nu$ here is the *astrophysical flux* rather than the *physical flux*,  so it is numerically equal to our $B_\nu$

**Comment by RobeReyes** [comment]
In my archive i have the same but the factor 2 i put out of the integral

**Comment by will-henney** [comment]
Final result of this is given here:

https://github.com/will-henney/globule-seminario/blob/main/m1-67/ionizing-luminosity.org

The result is $1.2 \times 10^{49}$ per second for $T_\mathrm{eff} = 33,000$ K and $R = 18 R_\odot$.  This is very close to the result fro WR model atmosphere models
