### ISSUE TITLE
 Deal with error propagation in the pressure balance plots

### ISSUE THREAD

**Issue by will-henney** [will-henney/globule-seminario#57]
For both the external and internal pressure balance plots, we need to include error bars on the points. For that, we need to carry out the following steps

1. Estimate the observational uncertainties on each empirical measurement
2. Calculate the propagation of those uncertainties to find the uncertainties in the final quantities that we are plotting

**Comment by will-henney** [comment]
## Step 1A - external pressure balance with stellar wind

Here, there are only 3 empirical measurements for the y axis:

* Shell brightness, $B_s$
* Shell radius, $r_s$
* Shell thickness, $H_s$

The x axis is just the projected radius, which has negligible uncertainties

**Comment by will-henney** [comment]
## Step 2A - internal pressure balance with the photoevaporation flow

The y axis depends on the same 3 quantities as above, plus the core measurements:

* Peak brightness, $B_0$
* Ionization front radius, $r_0$

The x axis depends on the ratio $r_s / r_0$.

**Comment by will-henney** [comment]
## Estimates of uncertainties in shell radius and thickness

This is estimated form intercomparison of the measurements on the HST and JWST images. We use a global value for all knots

**Comment by will-henney** [comment]
## Estimates of uncertainty in ionization front radius

This is the trickiest thing to calculate due to two factors:

* The sizes are comparable with the angular resolution of the image
* The relation between the width of the emission peak and the radius of the ionization front is not necessarily simple

To help with the first factor, we will not try to find the radii of individual knots, since we suspect that the variation in measured values is dominated by observational effects, rather than a true intrinsic variation in sizes. Instead, we will use the mean value over all knots. 

To help with the second, we will combine measurements from two different images: the H alpha image, which traces the ionized emission form the ionization front, and the combo-D image, which traces the PAH in the neutral core of the knot. 

So the nominal value of the radius will be the average of the mean values from the two images, and the uncertainty will be taken as the difference between these two mean values. 

Optionally, we could also calculate the s.e.m. of the individual distributions. This is the standard deviation divided by sqrt(N).

**Comment by will-henney** [comment]
## Estimates of uncertainty in the shell brightness

Since the shells are of similar brightness to the background, this is dominated by fluctuations in the background brightness. 

So, we can calculate the weighted dispersion of the residuals (observed image - model) as an estimate of this uncertainty. For weights, we can use the product of the weights that we used in the model fit (which privilege pixels close to the symmetry axis) and the value of the shell component (only) of the model (which will select only those pixels that lie in the shell). 

We can find the std as the sqrt of the weighted variance (weighted average of square of residuals):

```
residual = observed - model
weights = fitting_weights * shell_component_of_model
var = np.average(residual ** 2, weights=weights)
sigma = np.sqrt(var)
```

**Comment by will-henney** [comment]
## Estimates of uncertainty in the core brightness

In this case, we are probably not dominated by bg fluctuations. However, it might still be useful to use the weighted variance of the residuals to estimate the uncertainty. The only difference is that we use the core gaussian component of the model to multiply the weight.

Another factor that effects the core brightness is that it may be systematically underestimated if the emission from the ionization front is not spatially resolved.

**Comment by will-henney** [comment]
## Step 2: propagation of errors

For this, we can use the [uncertainties](https://uncertainties.readthedocs.io/en/latest/index.html) package, which will automatically do most of what we want.

**Comment by RobeReyes** [comment]
there is a first notebook [here](https://github.com/will-henney/globule-seminario/blob/main/m1-67/graficas%20con%20errore.ipynb)

**Comment by will-henney** [comment]
This is now all done in Roberto's thesis
